recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.home, name="home-workout"),
    path('category/<int:category_id>/', views.category, name="category"),
    path('cards/<int:id>/', views.card_training, name="card-training"),
    path('recipes/search/', views.search, name='search')
]

start/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/',include('authors.urls'))
]

urlpatterns+= static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

urlpatterns+= static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=65)
    
    def __str__(self):
        return self.name

class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')
    category = models.ForeignKey(Category, on_delete= models.SET_NULL, null = True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.title)}'
            self.slug = slug
        return super().save(*args, **kwargs)

authors/forms/recipe_form.py
from django import forms
from recipes.models import Recipe
from utils.django_forms import add_attr



class AuthorRecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__    (*args, **kwargs)
        add_attr(self.fields.get('preparation_steps'), 'class', 'span-2')
        add_attr(self.fields.get('cover'), 'class', 'span-2')

    class Meta:
        model = Recipe
        fields = 'title', 'description', 'preparation_time', \
            'preparation_time_unit', 'servings', 'servings_unit', \
            'preparation_steps', 'cover'
        widgets = {
            'cover': forms.FileInput(
                attrs={
                    'class': 'span-2'
                }
            ),
            'servings_unit': forms.Select(
                choices=(
                    ('Porções', 'Porções'),
                    ('Pedaços', 'Pedaços'),
                    ('Pessoas', 'Pessoas'),
                ),
            ),
            'preparation_time_unit': forms.Select(
                choices=(
                    ('Minutos', 'Minutos'),
                    ('Horas', 'Horas'),
                ),
            ),
        }

recipes/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from utils.recipes.factory import make_recipe
from .models import Recipe
from django.http import HttpResponse, Http404
from django.db.models import Q
from django.core.paginator import Paginator
from utils.pagination import make_pagination
from django.contrib import messages
import os

PER_PAGES = int(os.environ.get('PER_PAGES',6))

# Create your views here.
def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')
    page_obj,pagination_range = make_pagination(request,recipes,PER_PAGES)   

    return render(request,'recipes/pages/home.html',context={
        'recipes':page_obj,
        'pagination_range':pagination_range
    })



def category(request,category_id):
    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id
            ,is_published=True,).order_by('-id'))
    
    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGES)
    
    return render(request,'recipes/pages/category.html',context={
        'recipes':page_obj,
        'pagination_range':pagination_range,
        'title': f'{recipes[0].category.name} - Category'
    })

def card_training(request, id):
    recipe = get_object_or_404(Recipe, pk=id, is_published = True,)


    return render(request, 'recipes/pages/training-view.html', context={
        'recipe': recipe,
        'is_detail_page':True,
    })
def search(request):
    search_term = request.GET.get('q', '').strip()
    recipes = Recipe.objects.filter(
        Q(
        Q(title__icontains= search_term) |
        Q(description__icontains = search_term)),
        is_published= True
    ).order_by('-id')
    if not search_term:
        raise Http404()
    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGES)

    return render(request, 'recipes/pages/search.html',{
        'page_title':f'Search for "{search_term}"|',
        'search_term':search_term,
        'recipes':page_obj,
        'pagination_range': pagination_range,
        'additional_url_query': f'&q={search_term}',
        },)

recipes/templates/recipes/partials/cards.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'recipes:card-training' recipe.id %}">
        {% if recipe.cover %}
            <img src="{{ recipe.cover.url }}" alt="foto temporária">
        {% endif %}
        </a>
    </div>


    <div class="recipe-title-container">
        <a href={% url "recipes:card-training" recipe.id %}>
            <h2 class="recipe-title">{{recipe.title}}</h2>
        </a>
    </div>

    <div class="recipe-author">
        {% if recipe.author is not None %}
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author.first_name %}
                    {{recipe.author.first_name}}
                {% else %}
                    {{recipe.author.username}}
                {% endif %}
            </span>
        {% endif %}
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{recipe.created_at|date:'d/m/Y'}}
        </span>
        <span class="recipe-author-item">
            <a href="{% url "recipes:category" recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span>{{recipe.category.name}}</span>
            </a>
        </span>
    </div>

    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title">
                <i class="fas fa-stopwatch"></i> preparação
            </h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
            </div>
        </div>

        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title">
                <i class="fa-solid fa-bowl-food"></i> porções
            </h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>
    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url "recipes:card-training" recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class='execution-way'>
            {% if recipe.preparation_steps_is_html is True %}
                {{recipe.preparation_steps|safe}}
            {% else%}
                {{recipe.preparation_steps|linebreaksbr}}
            {% endif %}
        </div>
    {% endif %}

</div>